# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()

d1=np.array([1,2,3,4,5])

# Create a 2-dimensional NumPy array using np.array()
d2=np.array([[10,2,2,22,4],
            [40,5,0,60,0]])

# Create a 3-dimensional Numpy array using np.array()
d3=np.array([[[10,20,30],
             [40,50,60]],
            [[70,50,90],
            [75,85,95]]])

In [6]:
d1


array([1, 2, 3, 4, 5])

In [7]:
d2

array([[10,  2,  2, 22,  4],
       [40,  5,  0, 60,  0]])

In [8]:
d3

array([[[10, 20, 30],
        [40, 50, 60]],

       [[70, 50, 90],
        [75, 85, 95]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [10]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
np.ndim(d1),d1.dtype,np.size(d1),type(d1)

(1, dtype('int32'), 5, numpy.ndarray)

In [11]:
# Attributes of 2-dimensional array
np.ndim(d2),d2.dtype,np.size(d2),type(d2)

(2, dtype('int32'), 10, numpy.ndarray)

In [12]:
# Attributes of 3-dimensional array
np.ndim(d3),d3.dtype,np.size(d3),type(d3)

(3, dtype('int32'), 12, numpy.ndarray)

In [14]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df2=pd.DataFrame(d2)
df2

0  1  2   3  4
0  10  2  2  22  4
1  40  5  0  60  0

In [16]:
# Create an array of shape (10, 2) with only ones
np.ones(shape=(10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [24]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0,10,size=(7,2))

array([[1, 0],
       [9, 1],
       [5, 5],
       [9, 9],
       [4, 7],
       [4, 2],
       [3, 8]])

In [26]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.uniform(0,1,size=(3,5))

array([[0.83180735, 0.7783391 , 0.89903765, 0.55978591, 0.4378713 ],
       [0.92269136, 0.00737808, 0.75199942, 0.61747563, 0.81533284],
       [0.86621207, 0.28165831, 0.49127938, 0.38827072, 0.02256984]])

In [28]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10,size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [32]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
RR=np.random.randint(0,10,size=(3,7))
print(RR)
# Find the unique numbers in the array you just created
np.unique(RR)

[[0 7 2 2 0 4 9]
 [6 9 8 6 8 7 1]
 [0 6 6 7 4 2 7]]


array([0, 1, 2, 4, 6, 7, 8, 9])

In [33]:
# Find the 0'th index of the latest array you created
RR[0]

array([0, 7, 2, 2, 0, 4, 9])

In [36]:
# Get the first 2 rows of latest array you created
RR[:2]

array([[0, 7, 2, 2, 0, 4, 9],
       [6, 9, 8, 6, 8, 7, 1]])

In [37]:
# Get the first 2 values of the first 2 rows of the latest array
RR[:2,:2]

array([[0, 7],
       [6, 9]])

In [42]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
temp=np.random.randint(0,10,size=(3,5))
ones=np.ones((3,5))

In [43]:
temp

array([[7, 8, 4, 0, 2],
       [9, 7, 5, 7, 8],
       [3, 0, 0, 9, 3]])

In [57]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
ones.shape

(3, 5)

In [58]:
# Add the two arrays together
temp+ones

array([[ 8.,  9.,  5.,  1.,  3.],
       [10.,  8.,  6.,  8.,  9.],
       [ 4.,  1.,  1., 10.,  4.]])

In [65]:
# Create another array of ones of shape (5, 3)
ones1=np.ones((5,3))
ones1.shape

(5, 3)

In [60]:
# Try add the array of ones and the other most recent array together
ones1+ones

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [68]:
# Create another array of ones of shape (3, 5)
ones1=np.reshape(ones1,(3,5))

In [72]:
# Subtract the new array of ones from the other most recent array
ones-ones1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [73]:
# Multiply the ones array with the latest array
ones*temp

array([[7., 8., 4., 0., 2.],
       [9., 7., 5., 7., 8.],
       [3., 0., 0., 9., 3.]])

In [76]:
# Take the latest array to the power of 2 using '**'
%timeit temp**2

1.84 µs ± 20.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [77]:
# Do the same thing with np.square()
%timeit np.square(temp)

1.56 µs ± 14.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [78]:
# Find the mean of the latest array using np.mean()
np.mean(temp)

4.8

In [79]:
# Find the maximum of the latest array using np.max()
np.max(temp)

9

In [80]:
# Find the minimum of the latest array using np.min()
np.min(temp)

0

In [81]:
# Find the standard deviation of the latest array
np.std(temp)

3.2083225108042575

In [82]:
# Find the variance of the latest array
np.var(temp)

10.293333333333335

In [83]:
# Reshape the latest array to (3, 5, 1)
np.reshape(temp,(3,5,1))

array([[[7],
        [8],
        [4],
        [0],
        [2]],

       [[9],
        [7],
        [5],
        [7],
        [8]],

       [[3],
        [0],
        [0],
        [9],
        [3]]])

In [84]:
# Transpose the latest array
temp.T

array([[7, 9, 3],
       [8, 7, 0],
       [4, 5, 0],
       [0, 7, 9],
       [2, 8, 3]])

What does the transpose do?

In [86]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
r1=np.random.randint(0,10,size=(3,3))
r2=np.random.randint(0,10,size=(3,2))
r1

array([[0, 2, 1],
       [4, 9, 5],
       [6, 3, 6]])

In [87]:
r2

array([[7, 0],
       [5, 7],
       [4, 3]])

In [88]:
# Perform a dot product on the two newest arrays you created
np.dot(r1,r2)

array([[14, 17],
       [93, 78],
       [81, 39]])

In [89]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
r1=np.random.randint(0,10,size=(4,3))
r2=np.random.randint(0,10,size=(4,3))

In [90]:
# Perform a dot product on the two newest arrays you created
np.dot(r1,r2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [91]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(r1,r2.T)

array([[47, 43, 42, 47],
       [54, 64, 53, 40],
       [31, 30, 35, 38],
       [43, 78, 70, 30]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [97]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
r1=np.random.randint(0,10,size=(3,3))
r2=np.random.randint(0,10,size=(3,3))
r1

array([[8, 1, 1],
       [1, 5, 2],
       [8, 3, 0]])

In [98]:
r2

array([[3, 0, 4],
       [3, 7, 7],
       [6, 2, 0]])

In [99]:
# Compare the two arrays with '>'
r1>r2

array([[ True,  True, False],
       [False, False, False],
       [ True,  True, False]])

What happens when you compare the arrays with `>`?

In [100]:
# Compare the two arrays with '>='
r1>=r2

array([[ True,  True, False],
       [False, False, False],
       [ True,  True,  True]])

In [101]:
# Find which elements of the first array are greater than 7
r1>7

array([[ True, False, False],
       [False, False, False],
       [ True, False, False]])

In [102]:
# Which parts of each array are equal? (try using '==')
r1==r2

array([[False, False, False],
       [False, False, False],
       [False, False,  True]])

In [108]:
r1

array([[8, 1, 1],
       [1, 5, 2],
       [8, 3, 0]])

In [109]:
# Sort one of the arrays you just created in ascending order
np.sort(r1)

array([[1, 1, 8],
       [1, 2, 5],
       [0, 3, 8]])

In [110]:
# Sort the indexes of one of the arrays you just created
np.argsort(r1)

array([[1, 2, 0],
       [0, 2, 1],
       [2, 1, 0]], dtype=int64)

In [111]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(r1)

0

In [112]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(r1)

8

In [113]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argsort(r1,axis=0)

array([[1, 0, 2],
       [0, 2, 0],
       [2, 1, 1]], dtype=int64)

In [116]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argsort(r1,axis=1)

array([[1, 2, 0],
       [0, 2, 1],
       [2, 1, 0]], dtype=int64)

In [118]:
# Create an array of normally distributed random numbers
np.random.randn(10)

array([ 0.41811852, -1.88652805,  2.27334516,  0.14697465,  0.5396092 ,
       -1.49829564, -0.01144345,  0.41335409, -0.14089855,  0.87216186])

In [120]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(0,100,10,)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.